### ISSUE TITLE
Rumble support

### ISSUE THREAD

**Issue by robonxt** [SukkoPera/PsxNewLib#2]
Am interested in having rumble support. I see that you have the static bytes disabled for rumble. Any reason why, or is it too much of a hassle to make it support the motors?

**Comment by SukkoPera** [comment]
I didn't need rumble, so developing, testing and debugging it was just too much of a hassle, also because of the need for separate power I could not easily provide back then. Now with the [PsxControllerShield](https://github.com/SukkoPera/PsxControllerShield) it should be somewhat easier, but currently I do not have time for it.

Would you be interested in developing it yourself? I could send you a shield in case.

(The same applies to whoever would be willing to do it, of course :).)

**Comment by robonxt** [comment]
Sure! I'd be happy to try adding rumble support, if you don't mind a beginner helping out.

Also in my case, I was using a wireless controller, so I didn't have any need for a separate power source.

**Comment by SukkoPera** [comment]
OK, go ahead and feel free to ask when you're in trouble. I'll be on #openretroworks on FreeNode after 7pm UTC+2.

**Comment by katemonster33** [comment]
#10 pull request is up for this feature.

**Comment by SukkoPera** [comment]
Aaaaaaand... merged! I have just release v0.4.0, thanks a lot!
